model_name: aediff_restore
loss: l1
lr: 0.0001
color_range: 255
weight_decay: 1.0e-05
lr_scheduler: step
lr_decay_steps: 20
lr_decay_rate: 0.5
lr_decay_min_lr: 1.0e-05
checkpoint_loaddir: /share/program/dxs/RSISR/checkpoint
checkpoint_version: 0
load_v_num: 1
ch: 32
out_ch: 256
in_channels: 3
out_channels: 3
z_channels: 256
num_res_blocks: 10
attn_resolutions:
- 64
- 128
resamp_with_conv: true
resolution: 64
use_linear_attn: false
use_timestep: false
attn_type: vanilla
