data:
 target: data.data_interface.DInterface
 params:
  train_dataset_dir: /share/program/dxs/Database/data/pngimage_train_HR
  val_dataset_dir: /share/program/dxs/Database/data/pngimage2_valid_HR
  test_dataset_dir: /share/program/dxs/Database/data/pngimage2_valid_HR
  crop_size: 256
  upscale_factor: 4
  batch_size: 4
  wrap: bool
model:
 model_name: upscale_model
 color_range: 1
 lr: 8.0e-05
 loss: mse
 weight_decay: 1e-5
 lr_scheduler: 'step'
 lr_decay_steps: 20
 lr_decay_rate: 0.5
 lr_decay_min_lr: 1e-5
 checkpoint_loaddir: None
 checkpoint_version: 0
 load_v_num: 1
 best: True
 image_size: 256
 model_config:
  upsample:
   in_channels: 3
   out_channels: 3
   attn: 'sp_att'
   upscale_factor: 4
  encoder:
   model_path: "/share/program/dxs/RSISR/pretrain_weights"
  ddpm: 
   T: 1000
   beta_schedule: "linear"
  decoder:
   model_path: "/share/program/dxs/RSISR/pretrain_weights"
trainer:
 max_epochs: 100
 devices: 4
 precision: 'bf16'
 accelerator: "gpu"
 strategy: 'ddp_find_unused_parameters_true'
callbacks:
 lr_scheduler: step
other_params:
 trainer_stage: 'train'
 seed: 23