data:
 target: data.data_interface.DInterface
 params:
  train_dataset_dir: /share/program/dxs/Database/data/pngimage_train_HR
  val_dataset_dir: /share/program/dxs/Database/data/pngimage2_valid_HR
  test_dataset_dir: /share/program/dxs/Database/data/
  crop_size: 256
  upscale_factor: 4
  batch_size: 100
  wrap: bool
model:
 model_name: ddpm_model
 schedule_name: "linear_beta_schedule"
 timesteps: 1000
 beta_start: 0.0001
 beta_end: 0.02
 denoise_model: unet
 unet:
  image_size: 64
  channels: 3
  dim_mults: (1, 2, 4,)
 lr: 1.0e-04
 loss: l1
 weight_decay: 1e-5
 lr_scheduler: 'step'
 lr_decay_steps: 20
 lr_decay_rate: 0.5
 lr_decay_min_lr: 1e-5
 checkpoint_loaddir: /share/program/dxs/RSISR/checkpoint
 checkpoint_version: 0
 load_v_num: 1
trainer:
 max_epochs: 500
 gpus: 4
 precision: 16
 accelerator: "ddp_spawn"
callbacks:
 lr_scheduler: step
other_params:
 trainer_stage: 'train'