upsample:
 in_channels: 3
 out_channels: 3
 attn: 'ch_att'
 upscale_factor: 4
encoder:
 model_path: "/share/program/dxs/RSISR/pretrain_weights"
ddpm: 
 T: 1000
 beta_schedule: "linear"
decoder:
 model_path: "/share/program/dxs/RSISR/pretrain_weights"
img_size: 256
ch: 3