data:
 target: data.data_interface.DInterface
 params:
  batch_size: 100
  wrap: bool
  train:
    target: /share/program/dxs/Database/data/DIV2K_train_HR
  validation: 
    target: /share/program/dxs/Database/data/DIV2K_valid_HR
model:
 model_name: resnet_restore
 lr: 1.0e-04
 loss: l1
 weight_decay: 1e-5
 lr_scheduler: 'step'
 lr_decay_steps: 20
 lr_decay_rate: 0.5
 lr_decay_min_lr: 1e-5
 checkpoint_loaddir: /share/program/dxs/RSISR/checkpoint
 checkpoint_version: 0
 load_v_num: 1
 ch: 256
 out_ch: 1024
 in_channels: 4
 num_res_blocks: 10
 attn_resolutions: [256, 512]
 resamp_with_conv: True
 resolution: 256
 use_timestep: True
 use_linear_attn: False
 attn_type: 'vanilla'
trainer:
 max_epochs: 1000
 gpus: 4
 precision: 32
 accelerator: "ddp_spawn"
callbacks:
 lr_scheduler: step