data:
 target: data.data_interface.DInterface
 params:
  train_dataset_dir: /share/program/dxs/Database/data/pngimage_train_HR
  val_dataset_dir: /share/program/dxs/Database/data/pngimage2_valid_HR
  test_dataset_dir: none
  crop_size: 64
  upscale_factor: 2
  batch_size: 50
  wrap: bool
model:
 model_name: resnet_restore
 color_range: 255
 lr: 1.0e-04
 loss: l1
 weight_decay: 1e-5
 lr_scheduler: 'step'
 lr_decay_steps: 20
 lr_decay_rate: 0.5
 lr_decay_min_lr: 1e-5
 checkpoint_loaddir: /share/program/dxs/RSISR/checkpoint
 checkpoint_version: 0
 load_v_num: 1
 ch: 32
 out_ch: 256
 in_channels: 3
 num_res_blocks: 10
 attn_resolutions: [64, 128]
 resamp_with_conv: True
 resolution: 64
 use_linear_attn: False
 use_timestep: False
 attn_type: 'vanilla'
trainer:
 max_epochs: 1000
 gpus: 4
 precision: 16
 accelerator: "ddp_spawn"
callbacks:
 lr_scheduler: step