data:
 target: data.data_interface.DInterface
 params:
  train_dataset_dir: /share/program/dxs/Database/data/pngimage_train_HR
  val_dataset_dir: /share/program/dxs/Database/data/pngimage2_valid_HR
  test_dataset_dir: /share/program/dxs/Database/data
  crop_size: 224
  upscale_factor: 4
  batch_size: 4
  wrap: bool
model:
 model_name: vit_upscale
 color_range: 255
 lr: 1.0e-04
 loss: l1
 weight_decay: 1e-5
 lr_scheduler: 'step'
 lr_decay_steps: 20
 lr_decay_rate: 0.5
 lr_decay_min_lr: 1e-5
 checkpoint_loaddir: None
 checkpoint_version: None
 load_v_num: None
 image_size: 256
 model_config:
  img_size: 224
  ch: 3
  upsample:
   in_channels: 3
   out_channels: 3
   attn: 'ch_att'
   upscale_factor: 4
  ddpm: 
   T: 1000
   beta_schedule: "linear"
trainer:
 max_epochs: 200
 gpus: 4
 precision: 16
 accelerator: "ddp_spawn"
callbacks:
 lr_scheduler: step
other_params:
 trainer_stage: 'train'
 seed: 23