data:
 target: data.data_interface.DInterface
 params:
  train_dataset_dir: /share/program/dxs/Database/data/pngimage_train_HR
  val_dataset_dir: /share/program/dxs/Database/data/pngimage2_valid_HR
  test_dataset_dir: /share/program/dxs/Database/data/pngimage2_valid_HR
  original_size: 256
  crop_size: 224
  upscale_factor: 4
  batch_size: 4
  wrap: bool
  # 按类推理相关参数，含数据扩增
  type_name: agricultural
  n_augmentations: 3
  augment: False
  inference_mode: False
model:
 model_name: vit_upscalev2
 color_range: 1
 lr: 1.0e-4
 loss: mse
 weight_decay: 1.0e-5
 lr_scheduler: 'step'
 lr_decay_steps: 10
 lr_decay_rate: 0.5
 lr_T_max: 10
 min_lr: 2.0e-5
 checkpoint_loaddir: None
 checkpoint_version: 0
 load_v_num: 0
 best: True
 image_size: 256
 model_config:
  img_size: 256
  ch: 3
  upsample:
   in_channels: 3
   out_channels: 3
   attn: 'ch_att'
   upscale_factor: 4
  ddpm: 
   T: 1000
   beta_schedule: "linear"
  decoder:
   img_size: 256
   n_colors: 3
   patch_size: 1
   n_group: 1
   hidden_dim: 3
   n_feats: 16
   n_resblocks: 4
   n_resgroups: 2
   n_stb: 1
   stb:
    embed_dim: 16
    input_resolution: 256
    num_heads: [2,4,8,16]
    window_size: 4
    depths: [2,2,2,2]
   upsacle_factor: 4
   rgb_range: 1
trainer:
 max_epochs: 100
 devices: 4
 precision: 'bf16-mixed'
 accelerator: "gpu"
 strategy: 'ddp_find_unused_parameters_true'
callbacks:
 lr_scheduler: step
other_params:
 trainer_stage: 'train'
 seed: 23
 log_flag: 'v1'
 model_n: 'vit_v6'